### PR TITLE
no more survur crash pls

### PR DESCRIPTION
**Pull request by PhanaticD**

### CODE REVIEW

**Comment by RoboMWM** [comment]
Chunk should already be loaded at this time tho? Imma guess the recent Paper builds have been causing havoc for you as it has been for many others, but whatever.

**Comment by PhanaticD** [comment]
if they were loaded it got unloaded or something, thats the code area that showed up in a couple crashes

**Comment by RoboMWM** [comment]
Do you use `wait`?

**Comment by PhanaticD** [comment]
yea

**Pull request merged**
