### PR TITLE
Kewwwldown timer.

### PR DESCRIPTION
**Pull request by Markersx**
I'm new to java so it was all trial and error but tested this on my server and it seems to be working no errors in console all the commands worked and so does the cool down timer.

### CODE REVIEW

**Comment by RoboMWM** [comment]
There's already a cooldown? Not sure what you're trying to PR here.

**Comment by Markersx** [comment]
When ever you use /wild and its in cooldown it says "You must wait Soon seconds until you can use the command/sign again" because of `p.sendMessage(TooWildForEnums.translate(TooWildForEnums.COOLDOWN.replace("%TIME%", "Soon")));`

**Comment by RoboMWM** [comment]
Well technically we can set data in that metadata whatever but I guess a hashmap is just as good I suppose. I have some midterms this week, so I'll push and test near the end of this week. Otherwise, feel free to test your PR out (as you have already it seems) and try to break it.

**Comment by Markersx** [comment]
Because Eclipse gave me a warning "The static field should be accessed in a static way".

**Comment by RoboMWM** [comment]
Well ignore Eclipse's bad advice and revert it (I would but not at a dev machine right now).

**Comment by RoboMWM** [comment]
Eventually @LaxWasHere fixed it properly and without changing the project to static references.

**Pull request closed without merging**
