### PR TITLE
Fix NullPointerException caused when fired by a non-op user

### PR DESCRIPTION
**Pull request by Legoman99573**
Resolves NullPointerException fired when people who are not OP fire /wild

### CODE REVIEW

**Comment by RoboMWM** [comment]
Hmm. So, some server admins have it setup so players can only `/wild` in a particular world, hence why this permission isn't given by default. I do agree that `/wildtp` should be given by default to ops though (and maybe `/wild` as well).

Neither should be causing an NPE though...?

**Comment by Legoman99573** [comment]
When OP, NullPointerException doesnt occur, but when a non-op fires it, it would show up for some reason in game showing as "An internal error has occured". Adding default to both commands wound up resolving the issue for me after re-compiling the code.

**Comment by RoboMWM** [comment]
Um, the "default" value is false by default.

Can you please paste the stacktrace with this NPE?

**Comment by Legoman99573** [comment]
https://paste.md-5.net/wezimehupi.cs

**Comment by jyhsu2000** [comment]
> https://paste.md-5.net/wezimehupi.cs probably will be more helpful than the temp workaround i found.

Wrong project.
The plugin you're using is the following one. 
https://github.com/Qballl/WildernessTp

**Comment by Legoman99573** [comment]
oops, im dum

**Comment by RoboMWM** [comment]
Yea, this one's better, his has copied code from here.

**Pull request closed without merging**
