### PR TITLE
Extract RandomLocationSearchTask. Finish #40

### PR DESCRIPTION
**Pull request by jyhsu2000**
As said in #40, maybe it will be helpful if there is some way to get a random location without teleportation.
I tried to extract random location searching to RandomLocationSearchTask class.
This PR provides a way to get a random location without teleportation.
The following is a simple example to get a random location.
```java
FutureTask<Location> futureTask = RandomLocationSearchTask.search(world, player);
Location location = futureTask.get(5, TimeUnit.SECONDS);
```
Complete usage can be found in [getRandomeLocation](https://github.com/jyhsu2000/WildernessTp/blob/master/src/main/java/net/poweredbyhate/wildtp/TeleportGoneWild.java#L91) of `TeleportGoneWild`

---

PS.
- Implement new methods in 2b2bad9 is just for building project. Maybe API changed?
- `futureTask.get` will block the thread. It should be used in non-main thread.
- Most content of `RandomLocationSearchTask` is copied from `TeleportGoneWild` without changed.

### CODE REVIEW

**Comment by jyhsu2000** [comment]
Sorry about "force-push" and code style.
I did it because I just noticed you used `CRLF` as line ending.
And I tried to redo commits to match your code style, but in vain.
Even if I set eol in `.gitattributes` and disable `core.autocrlf` in my local repo, it still changed into `LF` when I pushed.

**Comment by RoboMWM** [comment]
Hmm, we do need a gitattributes. lol. Thanks tho.

**Comment by RoboMWM** [comment]
You can try setting to `crlf`

Otherwise I can just try fixing it to be `lf`.

Feel free to force push your own PRs though that's no problem.

**Comment by jyhsu2000** [comment]
Almost finished.
The diff page to good to read now I think.
Please help for review.

And I found the key point.
In fact, `core.autocrlf` did working well when I set it to false.
But there are some inconsistencies at the line endings in the project,
e.g.
`JohnBonifield.java` use `LF`
`TeleportGoneWild.java` use `CRLF`

Maybe we still need `.gitattributes`, `.editorconfig` or something to make it keeping consistent.

**Comment by RoboMWM** [comment]
Yea, I'll probably normalize file endings after pulling this PR since it looks like you already went through the trouble lol.

I normally use gitattributes but since I didn't create this project it seems my editor went rogue.

**Comment by jyhsu2000** [comment]
Never mind.
I just want to split random location getting and teleportation.
And let other plugins can use it easily.

I'm glad that you are going to unified the code style.

I think this PR is finished now.
In my expectation, there will be nothing changed when using this plugin directly.
But there is a new way provided for getting a random location without teleportation.

**Comment by RoboMWM** [comment]
Cool, thank you for letting me know you're finished with the PR.

**Pull request merged**
